remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

title: Amateur Satellites
description: Amateur Satellites and Satellite Tracking
url: https://satellites.browxy.com

relative_links:
  enabled: true
  collections: true

color_scheme: "dark"
search_enabled: true
nav_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 1985-2025 Pedro Converso. Distributed by an <a href=\"https://github.com/bxyteam/satellites-lu7abf/blob/main/LICENSE\">MIT license.</a>"